### ISSUE TITLE
Error building classpath: Could not find artifcat net.glowstone:glowstone:jar:2021.7.0-SNAPSHOT in central

### ISSUE THREAD

**Issue by dpetranek** [lambdaisland/witchcraft#2]
Hello,

I started watching the Clojure Meets Minecraft video and wanted to follow along, however I get a classpath error when I try to Cider-jack-in with the following `deps.edn`:

```
{:deps {:deps {com.lambdaisland/witchcraft {:mvn/version "0.0.24"}}}
```

```
[nREPL] Starting server via /run/current-system/sw/bin/clojure -Sdeps '{:deps {nrepl/nrepl {:mvn/version "0.8.3"} refactor-nrepl/refactor-nrepl {:mvn/version "2.5.1"} cider/cider-nrepl {:mvn/version "0.26.0"}} :aliases {:cider/nrepl {:main-opts ["-m" "nrepl.cmdline" "--middleware" "[refactor-nrepl.middleware/wrap-refactor,cider.nrepl/cider-middleware]"]}}}' -M:cider/nrepl
error in process sentinel: nrepl-server-sentinel: Could not start nREPL server: Error building classpath. Could not find artifact net.glowstone:glowstone:jar:2021.7.0-SNAPSHOT in central (https://repo1.maven.org/maven2/)

error in process sentinel: Could not start nREPL server: Error building classpath. Could not find artifact net.glowstone:glowstone:jar:2021.7.0-SNAPSHOT in central (https://repo1.maven.org/maven2/)
```

I was able to fix it by purloining the maven repo from this project. I'm not sure why it didn't work properly but thought you ought to know.

```
{:deps {com.lambdaisland/witchcraft {:mvn/version "0.0.24"}}
:mvn/repos
 {"glowstone-repo" {:url "https://repo.glowstone.net/content/repositories/snapshots/"}}
}
```

Also, fantastic project! This looks like a ton of fun!

**Comment by green-coder** [comment]
I confirm the error, and the provided solution works.

**Comment by plexus** [comment]
Thanks, someone also pointed this out on YouTube as well, and I can indeed reproduce it after clearing Glowstone from `~/.m2`. I added a section to the README about this

https://github.com/lambdaisland/witchcraft#installation

I've also asked in `#tools.deps` on Clojurians what's going on, since we do declare these [in our pom.xml](https://github.com/lambdaisland/witchcraft/blob/main/pom.xml#L91-L95), and from Maven's docs it sounds like it should pick those up, but maybe Clojure CLI doesn't.

If so then I'm not sure what the best solution is, I may just push the necessary dependencies to Clojars under our own groupId and use those. That could be attractive because it also allows us to not depend on mutable `-SNAPSHOT` versions.

**Comment by plexus** [comment]
Seems tools.dep deliberately does not recur into dependent's repos. I'll leave the instructions to add them explicitly for now and may revisit this in the future. Will leave this open for a while for people coming here after seeing the video.
